In [ ]:
import pandas as pd

df = pd.read_csv(r"answer_paper.csv", index_col=0)
df

,2019_70_1,2019_70_2,2019_70_3,2019_70_4,2020_71_1,2020_71_2,2020_71_3,2020_71_4,2021_72_1,2021_72_2,2021_72_3,2021_72_4,2022_73_1,2022_73_2,2022_73_3,2022_73_4,2023_74_1,2023_74_2,2023_74_3,2023_74_4
1,4,5.0,5.0,3.0,2,2.0,2.0,4.0,4,5.0,5.0,5.0,2,3.0,5.0,1.0,5,3.0,1.0,1.0
2,2,2.0,2.0,2.0,4,1.0,2.0,3.0,3,4.0,4.0,4.0,1,4.0,1.0,4.0,4,2.0,4.0,3.0
3,2,3.0,4.0,4.0,1,3.0,3.0,5.0,5,5.0,4.0,3.0,4,3.0,3.0,5.0,2,5.0,5.0,4.0
4,1,2.0,5.0,5.0,4,2.0,5.0,3.0,4,5.0,5.0,5.0,1,3.0,4.0,1.0,5,4.0,5.0,5.0
5,4,5.0,1.0,1.0,5,1.0,3.0,1.0,3,5.0,2.0,4.0,1,2.0,1.0,4.0,5,2.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,5,NaN,NaN,NaN,2,NaN,NaN,NaN,4,NaN,NaN,NaN,5,NaN,NaN,NaN,1,NaN,NaN,NaN
97,5,NaN,NaN,NaN,4,NaN,NaN,NaN,5,NaN,NaN,NaN,1,NaN,NaN,NaN,4,NaN,NaN,NaN
98,4,NaN,NaN,NaN,5,NaN,NaN,NaN,5,NaN,NaN,NaN,1,NaN,NaN,NaN,4,NaN,NaN,NaN
99,2,NaN,NaN,NaN,2,NaN,NaN,NaN,1,NaN,NaN,NaN,2,NaN,NaN,NaN,4,NaN,NaN,NaN
100,4,NaN,NaN,NaN,4,NaN,NaN,NaN,2,NaN,NaN,NaN,1,NaN,NaN,NaN,3,NaN,NaN,NaN

In [2]:
column_pairs_by_year = {}

for col in df.columns:
    match = pd.Series(col).str.extract(r'(\d{4})_(\d{2})_(\d{1})')  # Updated regular expression pattern
    if not match.empty:
        year, _, test_no = match.values[0]  # Extract all three values from the match
        if test_no in ['3', '4']:  # 3번 또는 4번 시험지에 해당하는 경우
            if year not in column_pairs_by_year:
                column_pairs_by_year[year] = {'3': [], '4': []}
            column_pairs_by_year[year][test_no].append(col)

# 각 연도에서 3번과 4번 시험지 컬럼이 모두 있는 경우만 쌍으로 추출
column_pairs = []
for year, tests in column_pairs_by_year.items():
    if tests['3'] and tests['4']:  # 3번과 4번 시험지 컬럼이 모두 존재하는 경우
        column_pairs.extend([(col_3, col_4) for col_3 in tests['3'] for col_4 in tests['4']])

# 결과 확인
column_pairs

[('2019_70_3', '2019_70_4'),
 ('2020_71_3', '2020_71_4'),
 ('2021_72_3', '2021_72_4'),
 ('2022_73_3', '2022_73_4'),
 ('2023_74_3', '2023_74_4')]

In [3]:
df_expanded = pd.DataFrame(index=range(1, 141))
df_expanded = pd.concat([df_expanded, df], axis=1)
for column_3, column_4 in column_pairs:
    print(column_3, column_4)
    column_3_extended = pd.concat([pd.Series(df[column_3].iloc[:77]), pd.Series(df[column_4]).iloc[:63]], ignore_index=True)
    column_3_extended.index = range(1, 141)

    column_4_adjusted = pd.Series(df[column_4]).iloc[63:83].reset_index(drop=True)
    column_4_adjusted.index = range(1, 21)

    df_expanded[column_3] = column_3_extended
    df_expanded[column_4] = column_4_adjusted
df_expanded.to_csv("answer.csv")

2019_70_3 2019_70_4
2020_71_3 2020_71_4
2021_72_3 2021_72_4
2022_73_3 2022_73_4
2023_74_3 2023_74_4

In [4]:
df_expanded

,2019_70_1,2019_70_2,2019_70_3,2019_70_4,2020_71_1,2020_71_2,2020_71_3,2020_71_4,2021_72_1,2021_72_2,2021_72_3,2021_72_4,2022_73_1,2022_73_2,2022_73_3,2022_73_4,2023_74_1,2023_74_2,2023_74_3,2023_74_4
1,4.0,5.0,5.0,1.0,2.0,2.0,2.0,2.0,4.0,5.0,5.0,2.0,2.0,3.0,5.0,2.0,5.0,3.0,1.0,5.0
2,2.0,2.0,2.0,3.0,4.0,1.0,2.0,3.0,3.0,4.0,4.0,2.0,1.0,4.0,1.0,1.0,4.0,2.0,4.0,4.0
3,2.0,3.0,4.0,3.0,1.0,3.0,3.0,1.0,5.0,5.0,4.0,3.0,4.0,3.0,3.0,2.0,2.0,5.0,5.0,3.0
4,1.0,2.0,5.0,4.0,4.0,2.0,5.0,4.0,4.0,5.0,5.0,3.0,1.0,3.0,4.0,5.0,5.0,4.0,5.0,4.0
5,4.0,5.0,1.0,4.0,5.0,1.0,3.0,5.0,3.0,5.0,2.0,3.0,1.0,2.0,1.0,5.0,5.0,2.0,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,NaN,NaN,5.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,4.0,NaN
137,NaN,NaN,3.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,4.0,NaN
138,NaN,NaN,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN
139,NaN,NaN,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,5.0,NaN
140,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,4.0,NaN